# Generated by Django 2.1.5 on 2019-02-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumahsakit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='nomor_telepon',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='alamat',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nomor_telepon',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='resep',
            name='total_harga',
            field=models.CharField(max_length=25),
        ),
    ]
