# Generated by Django 2.1.5 on 2019-02-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebunbinatang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjaga',
            name='nomor_telepon',
            field=models.CharField(max_length=25),
        ),
    ]
